### ISSUE TITLE
error /opt/build/repo/builder/node_modules/@ahrefs/bs-emotion-ppx: Command failed.

### ISSUE THREAD

**Issue by peterpme** [ahrefs/bs-emotion#37]
I'm not sure if there's something that can be done but noticed I've been getting htis error on CI:

```
3:52:11 PM: error /opt/build/repo/builder/node_modules/@ahrefs/bs-emotion-ppx: Command failed.
3:52:11 PM: Exit code: 1
3:52:11 PM: Command: node ./postinstall.js
3:52:11 PM: Arguments:
3:52:11 PM: Directory: /opt/build/repo/builder/node_modules/@ahrefs/bs-emotion-ppx
3:52:11 PM: Output:
3:52:11 PM: Could not create _export folder
3:52:11 PM: error: Error: EEXIST: file already exists, mkdir '/opt/build/repo/builder/node_modules/@ahrefs/bs-emotion-ppx/3'
3:52:11 PM: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
3:52:20 PM: warning Error running install script for optional dependency: "/opt/build/repo/builder/node_modules/bufferutil: Command failed.
3:52:20 PM: Exit code: 1
3:52:20 PM: Command: node-gyp rebuild
3:52:20 PM: Arguments:
3:52:20 PM: Directory: /opt/build/repo/builder/node_modules/bufferutil
3:52:20 PM: Output:
3:52:20 PM: gyp info it worked if it ends with ok
3:52:20 PM: gyp info using node-gyp@5.0.5
3:52:20 PM: gyp info using node@12.14.1 | linux | x64
3:52:20 PM: gyp info find Python using Python version 2.7.6 found at \"/opt/buildhome/python2.7/bin/python\"
3:52:20 PM: gyp http GET https://nodejs.org/download/release/v12.14.1/node-v12.14.1-headers.tar.gz
3:52:20 PM: gyp http 200 https://nodejs.org/download/release/v12.14.1/node-v12.14.1-headers.tar.gz
3:52:20 PM: gyp http GET https://nodejs.org/download/release/v12.14.1/SHASUMS256.txt
3:52:20 PM: gyp http 200 https://nodejs.org/download/release/v12.14.1/SHASUMS256.txt
3:52:20 PM: gyp info spawn /opt/buildhome/python2.7/bin/python
3:52:20 PM: gyp info spawn args [
3:52:20 PM: gyp info spawn args   '/opt/buildhome/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
3:52:20 PM: gyp info spawn args   'binding.gyp',
3:52:20 PM: gyp info spawn args   '-f',
3:52:20 PM: gyp info spawn args   'make',
3:52:20 PM: gyp info spawn args   '-I',
3:52:20 PM: gyp info spawn args   '/opt/build/repo/builder/node_modules/bufferutil/build/config.gypi',
3:52:20 PM: gyp info spawn args   '-I',
3:52:20 PM: gyp info spawn args   '/opt/buildhome/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
3:52:20 PM: gyp info spawn args   '-I',
3:52:20 PM: gyp info spawn args   '/opt/buildhome/.cache/node-gyp/12.14.1/include/node/common.gypi',
3:52:20 PM: gyp info spawn args   '-Dlibrary=shared_library',
3:52:20 PM: gyp info spawn args   '-Dvisibility=default',
3:52:20 PM: gyp info spawn args   '-Dnode_root_dir=/opt/buildhome/.cache/node-gyp/12.14.1',
3:52:20 PM: gyp info spawn args   '-Dnode_gyp_dir=/opt/buildhome/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp',
3:52:20 PM: gyp info spawn args   '-Dnode_lib_file=/opt/buildhome/.cache/node-gyp/12.14.1/<(target_arch)/node.lib',
3:52:20 PM: gyp info spawn args   '-Dmodule_root_dir=/opt/build/repo/builder/node_modules/bufferutil',
3:52:20 PM: gyp info spawn args   '-Dnode_engine=v8',
3:52:20 PM: gyp info spawn args   '--depth=.',
3:52:20 PM: gyp info spawn args   '--no-parallel',
3:52:20 PM: gyp info spawn args   '--generator-output',
3:52:20 PM: gyp info spawn args   'build',
3:52:20 PM: gyp info spawn args   '-Goutput_dir=.'
3:52:20 PM: gyp info spawn args ]
3:52:20 PM: gyp info spawn make
3:52:20 PM: gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
3:52:20 PM: make: Entering directory `/opt/build/repo/builder/node_modules/bufferutil/build'
3:52:20 PM:   CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
3:52:20 PM: ../src/bufferutil.cc:25:30: error: ‘v8::Handle’ has not been declared
3:52:20 PM:    static void Initialize(v8::Handle<v8::Object> target)
3:52:20 PM:                               ^
3:52:20 PM: ../src/bufferutil.cc:25:36: error: expected ‘,’ or ‘...’ before ‘<’ token
3:52:20 PM:    static void Initialize(v8::Handle<v8::Object> target)
3:52:20 PM:                                     ^
3:52:20 PM: ../src/bufferutil.cc: In static member function ‘static void BufferUtil::Initialize(int)’:
3:52:20 PM: ../src/bufferutil.cc:33:14: error: ‘target’ was not declared in this scope
3:52:20 PM:      Nan::Set(target, Nan::New<String>(\"BufferUtil\").ToLocalChecked(), t->GetFunction());
3:52:20 PM:               ^
3:52:20 PM: ../src/bufferutil.cc:33:86: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
3:52:20 PM:      Nan::Set(target, Nan::New<String>(\"BufferUtil\").ToLocalChecked(), t->GetFunction());
3:52:20 PM:                                                                                       ^
3:52:20 PM: ../src/bufferutil.cc:33:86: note: candidate is:
3:52:20 PM: In file included from ../src/bufferutil.cc:7:0:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:5995:46: note: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
3:52:20 PM:    V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
3:52:20 PM:                                               ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:5995:46: note:   candidate expects 1 argument, 0 provided
3:52:20 PM: ../src/bufferutil.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BufferUtil::Merge(Nan::NAN_METHOD_ARGS_TYPE)’:
3:52:20 PM: ../src/bufferutil.cc:49:49: error: no matching function for call to ‘v8::Value::ToObject()’
3:52:20 PM:      Local<Object> bufferObj = info[0]->ToObject();
3:52:20 PM:                                                  ^
3:52:20 PM: ../src/bufferutil.cc:49:49: note: candidates are:
3:52:20 PM: In file included from ../src/bufferutil.cc:7:0:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
3:52:20 PM:    V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
3:52:20 PM:                                             ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
3:52:20 PM: In file included from /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
3:52:20 PM:                  from /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:25,
3:52:20 PM:                  from ../src/bufferutil.cc:7:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
3:52:20 PM:                  Local<Object> ToObject(Isolate* isolate) const);
3:52:20 PM:                                ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
3:52:20 PM:    declarator __attribute__((deprecated(message)))
3:52:20 PM:    ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
3:52:20 PM:                  Local<Object> ToObject(Isolate* isolate) const);
3:52:20 PM:                                ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
3:52:20 PM:    declarator __attribute__((deprecated(message)))
3:52:20 PM:    ^
3:52:20 PM: ../src/bufferutil.cc:56:39: warning: ‘v8::Local<v8::Value> v8::Object::Get(uint32_t)’ is deprecated (declared at /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:3461): Use maybe version [-Wdeprecated-declarations]
3:52:20 PM:        Local<Object> src = array->Get(i)->ToObject();
3:52:20 PM:                                        ^
3:52:20 PM: ../src/bufferutil.cc:56:51: error: no matching function for call to ‘v8::Value::ToObject()’
3:52:20 PM:        Local<Object> src = array->Get(i)->ToObject();
3:52:20 PM:                                                    ^
3:52:20 PM: ../src/bufferutil.cc:56:51: note: candidates are:
3:52:20 PM: In file included from ../src/bufferutil.cc:7:0:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
3:52:20 PM:    V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
3:52:20 PM:                                             ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
3:52:20 PM: In file included from /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
3:52:20 PM:                  from /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:25,
3:52:20 PM:                  from ../src/bufferutil.cc:7:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
3:52:20 PM:                  Local<Object> ToObject(Isolate* isolate) const);
3:52:20 PM:                                ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
3:52:20 PM:    declarator __attribute__((deprecated(message)))
3:52:20 PM:    ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
3:52:20 PM:                  Local<Object> ToObject(Isolate* isolate) const);
3:52:20 PM:                                ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
3:52:20 PM:    declarator __attribute__((deprecated(message)))
3:52:20 PM:    ^
3:52:20 PM: ../src/bufferutil.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BufferUtil::Unmask(Nan::NAN_METHOD_ARGS_TYPE)’:
3:52:20 PM: ../src/bufferutil.cc:67:50: error: no matching function for call to ‘v8::Value::ToObject()’
3:52:20 PM:      Local<Object> buffer_obj = info[0]->ToObject();
3:52:20 PM:                                                   ^
3:52:20 PM: ../src/bufferutil.cc:67:50: note: candidates are:
3:52:20 PM: In file included from ../src/bufferutil.cc:7:0:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
3:52:20 PM:    V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
3:52:20 PM:                                             ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
3:52:20 PM: In file included from /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
3:52:20 PM:                  from /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:25,
3:52:20 PM:                  from ../src/bufferutil.cc:7:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
3:52:20 PM:                  Local<Object> ToObject(Isolate* isolate) const);
3:52:20 PM:                                ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
3:52:20 PM:    declarator __attribute__((deprecated(message)))
3:52:20 PM:    ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
3:52:20 PM:                  Local<Object> ToObject(Isolate* isolate) const);
3:52:20 PM:                                ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
3:52:20 PM:    declarator __attribute__((deprecated(message)))
3:52:20 PM:    ^
3:52:20 PM: ../src/bufferutil.cc:69:48: error: no matching function for call to ‘v8::Value::ToObject()’
3:52:20 PM:      Local<Object> mask_obj = info[1]->ToObject();
3:52:20 PM:                                                 ^
3:52:20 PM: ../src/bufferutil.cc:69:48: note: candidates are:
3:52:20 PM: In file included from ../src/bufferutil.cc:7:0:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
3:52:20 PM:    V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
3:52:20 PM:                                             ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
3:52:20 PM: In file included from /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
3:52:20 PM:                  from /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:25,
3:52:20 PM:                  from ../src/bufferutil.cc:7:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
3:52:20 PM:                  Local<Object> ToObject(Isolate* isolate) const);
3:52:20 PM:                                ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
3:52:20 PM:    declarator __attribute__((deprecated(message)))
3:52:20 PM:    ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
3:52:20 PM:                  Local<Object> ToObject(Isolate* isolate) const);
3:52:20 PM:                                ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
3:52:20 PM:    declarator __attribute__((deprecated(message)))
3:52:20 PM:    ^
3:52:20 PM: ../src/bufferutil.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BufferUtil::Mask(Nan::NAN_METHOD_ARGS_TYPE)’:
3:52:20 PM: ../src/bufferutil.cc:88:50: error: no matching function for call to ‘v8::Value::ToObject()’
3:52:20 PM:      Local<Object> buffer_obj = info[0]->ToObject();
3:52:20 PM:                                                   ^
3:52:20 PM: ../src/bufferutil.cc:88:50: note: candidates are:
3:52:20 PM: In file included from ../src/bufferutil.cc:7:0:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
3:52:20 PM:    V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
3:52:20 PM:                                             ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
3:52:20 PM: In file included from /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
3:52:20 PM:                  from /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:25,
3:52:20 PM:                  from ../src/bufferutil.cc:7:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
3:52:20 PM:                  Local<Object> ToObject(Isolate* isolate) const);
3:52:20 PM:                                ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
3:52:20 PM:    declarator __attribute__((deprecated(message)))
3:52:20 PM:    ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
3:52:20 PM:                  Local<Object> ToObject(Isolate* isolate) const);
3:52:20 PM:                                ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
3:52:20 PM:    declarator __attribute__((deprecated(message)))
3:52:20 PM:    ^
3:52:20 PM: ../src/bufferutil.cc:89:48: error: no matching function for call to ‘v8::Value::ToObject()’
3:52:20 PM:      Local<Object> mask_obj = info[1]->ToObject();
3:52:20 PM:                                                 ^
3:52:20 PM: ../src/bufferutil.cc:89:48: note: candidates are:
3:52:20 PM: In file included from ../src/bufferutil.cc:7:0:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
3:52:20 PM:    V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
3:52:20 PM:                                             ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
3:52:20 PM: In file included from /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
3:52:20 PM:                  from /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:25,
3:52:20 PM:                  from ../src/bufferutil.cc:7:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
3:52:20 PM:                  Local<Object> ToObject(Isolate* isolate) const);
3:52:20 PM:                                ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
3:52:20 PM:    declarator __attribute__((deprecated(message)))
3:52:20 PM:    ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
3:52:20 PM:                  Local<Object> ToObject(Isolate* isolate) const);
3:52:20 PM:                                ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
3:52:20 PM:    declarator __attribute__((deprecated(message)))
3:52:20 PM:    ^
3:52:20 PM: ../src/bufferutil.cc:91:50: error: no matching function for call to ‘v8::Value::ToObject()’
3:52:20 PM:      Local<Object> output_obj = info[2]->ToObject();
3:52:20 PM:                                                   ^
3:52:20 PM: ../src/bufferutil.cc:91:50: note: candidates are:
3:52:20 PM: In file included from ../src/bufferutil.cc:7:0:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
3:52:20 PM:    V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
3:52:20 PM:                                             ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
3:52:20 PM: In file included from /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
3:52:20 PM:                  from /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:25,
3:52:20 PM:                  from ../src/bufferutil.cc:7:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
3:52:20 PM:                  Local<Object> ToObject(Isolate* isolate) const);
3:52:20 PM:                                ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
3:52:20 PM:    declarator __attribute__((deprecated(message)))
3:52:20 PM:    ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
3:52:20 PM:                  Local<Object> ToObject(Isolate* isolate) const);
3:52:20 PM:                                ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
3:52:20 PM:    declarator __attribute__((deprecated(message)))
3:52:20 PM:    ^
3:52:20 PM: ../src/bufferutil.cc:92:51: error: no matching function for call to ‘v8::Value::Int32Value()’
3:52:20 PM:      unsigned int dataOffset = info[3]->Int32Value();
3:52:20 PM:                                                    ^
3:52:20 PM: ../src/bufferutil.cc:92:51: note: candidate is:
3:52:20 PM: In file included from ../src/bufferutil.cc:7:0:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const
3:52:20 PM:    V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
3:52:20 PM:                                         ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
3:52:20 PM: ../src/bufferutil.cc:93:47: error: no matching function for call to ‘v8::Value::Int32Value()’
3:52:20 PM:      unsigned int length = info[4]->Int32Value();
3:52:20 PM:                                                ^
3:52:20 PM: ../src/bufferutil.cc:93:47: note: candidate is:
3:52:20 PM: In file included from ../src/bufferutil.cc:7:0:
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const
3:52:20 PM:    V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
3:52:20 PM:                                         ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
3:52:20 PM: ../src/bufferutil.cc: At global scope:
3:52:20 PM: ../src/bufferutil.cc:114:12: error: variable or field ‘init’ declared void
3:52:20 PM:  void init (Handle<Object> target)
3:52:20 PM:             ^
3:52:20 PM: ../src/bufferutil.cc:114:12: error: ‘Handle’ was not declared in this scope
3:52:20 PM: ../src/bufferutil.cc:114:25: error: expected primary-expression before ‘>’ token
3:52:20 PM:  void init (Handle<Object> target)
3:52:20 PM:                          ^
3:52:20 PM: ../src/bufferutil.cc:114:27: error: ‘target’ was not declared in this scope
3:52:20 PM:  void init (Handle<Object> target)
3:52:20 PM:                            ^
3:52:20 PM: In file included from ../src/bufferutil.cc:8:0:
3:52:20 PM: ../src/bufferutil.cc:120:25: error: ‘init’ was not declared in this scope
3:52:20 PM:  NODE_MODULE(bufferutil, init)
3:52:20 PM:                          ^
3:52:20 PM: /opt/buildhome/.cache/node-gyp/12.14.1/include/node/node.h:560:36: note: in definition of macro ‘NODE_MODULE_X’
3:52:20 PM:        (node::addon_register_func) (regfunc),                          \\\n                                    ^
3:52:20 PM: ../src/bufferutil.cc:120:1: note: in expansion of macro ‘NODE_MODULE’
3:52:20 PM:  NODE_MODULE(bufferutil, init)
3:52:20 PM:  ^
3:52:20 PM: make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
3:52:20 PM: make: Leaving directory `/opt/build/repo/builder/node_modules/bufferutil/build'
3:52:20 PM: gyp ERR! build error
3:52:20 PM: gyp ERR! stack Error: `make` failed with exit code: 2
3:52:20 PM: gyp ERR! stack     at ChildProcess.onExit (/opt/buildhome/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
3:52:20 PM: gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
3:52:20 PM: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
3:52:20 PM: gyp ERR! System Linux 4.14.65+
3:52:20 PM: gyp ERR! command \"/opt/buildhome/.nvm/versions/node/v12.14.1/bin/node\" \"/opt/buildhome/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
3:52:20 PM: gyp ERR! cwd /opt/build/repo/builder/node_modules/bufferutil
3:52:20 PM: gyp ERR! node -v v12.14.1
3:52:20 PM: gyp ERR! node-gyp -v v5.0.5
3:52:20 PM: gyp ERR! not ok"
3:52:20 PM: info This module is OPTIONAL, you can safely ignore this error
3:52:22 PM: warning Error running install script for optional dependency: "/opt/build/repo/builder/node_modules/utf-8-validate: Command failed.
```

**Comment by jchavarri** [comment]
@peterpme Are you running multiple installations calling `yarn install` in multiple packages simultaneously, maybe?

Or alternatively, do you have a monorepo setup?

We could quickly fix the issue by making the `_export` folder creation more relaxed:

https://github.com/ahrefs/bs-emotion/blob/2909b029e1dd0091bd4bd981ea4cd73c61608ea8/.ci/bs-emotion-ppx/release-postinstall.js#L152-L156

But I want to understand why in your case the `postinstall` script is being called in a `node_modules` folder that was installed already —as the `_export` folder is there already.

**Comment by peterpme** [comment]
Hey @jchavarri sorry for the delay!

Yes we have a monorepo git setup but we aren't sharing the code between any other packages / folders

We _do_ have a package called `postinstall-postinstall` required for `patch-package`. I wonder if that's the problem?

**Comment by jchavarri** [comment]
@peterpme It seems that `patch-package` could be calling postinstall for packages that were already installed.

I published a temporary version of the `bs-emotion-ppx` package that changes the postinstall script so it does nothing if the `_export` folder is already there, to prevent failures when `node postinstall` is called on an already install package: `1.0.2-dev.1`.

You can add that version to your `package.json`, only for `bs-emotion-ppx` package, not need to change `bs-emotion`. Let's see if that fixes the problem mentioned above and helps us understand what's going on.

**Comment by peterpme** [comment]
Hey @jchavarri thank you so much! so far so good :) sorry for the delay i wanted to make sure things were working

**Comment by peterpme** [comment]
Hey @jchavarri some updates - not sure what's changed but now I'm getting this:

```
[4/4] Building fresh packages...
error /home/circleci/draftbit/builder/node_modules/@ahrefs/bs-emotion-ppx: Command failed.
Exit code: 1
Command: node ./postinstall.js
Arguments: 
Directory: /home/circleci/draftbit/builder/node_modules/@ahrefs/bs-emotion-ppx
Output:
error: Error: EEXIST: file already exists, mkdir '/home/circleci/draftbit/builder/node_modules/@ahrefs/bs-emotion-ppx/3'
```

Thanks!

**Comment by jchavarri** [comment]
@peterpme just to double check, are you using `1.0.2-dev.1`? In theory that version had a fix precisely for this error, see https://github.com/ahrefs/bs-emotion/pull/38.

**Comment by peterpme** [comment]
Yes, I'm using that! :) Thanks

**Comment by peterpme** [comment]
Hey @jchavarri so after some time (lol) this seems to be coming back:

```
error /home/circleci/draftbit/builder/node_modules/@ahrefs/bs-emotion-ppx: Command failed.

Exit code: 1

Command: node ./postinstall.js

Arguments: 

Directory: /home/circleci/draftbit/builder/node_modules/@ahrefs/bs-emotion-ppx

Output:

Could not create _export folder because the folder exists already, binaries will not be copied

error: Error: EEXIST: file already exists, mkdir '/home/circleci/draftbit/builder/node_modules/@ahrefs/bs-emotion-ppx/3'

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I actually removed patch-package and postinstall-postinstall but opencollective-postinstall started showing up and i think that's causing the issues now 😅 

i think it has to do with `bs-emotion-ppx/3`
