### ISSUE TITLE
Binary Request: Darwin/ARM64

### ISSUE THREAD

**Issue by pckilgore** [ahrefs/bs-emotion#53]
I.E., Apple's new M1 arch

```
Command: node ./copyPlatformBinaryInPlace.js
Arguments:
Directory: /Users/patrick/code/draftbit/draftbit/builder/node_modules/@ahrefs/bs-emotion-ppx
Output:
bs-emotion-ppx does not support this platform :(

bs-emotion-ppx comes prepacked as built binaries to avoid large
dependencies at build-time.

If you want bs-emotion-ppx to support this platform natively,
please open an issue at our repository, linked above. Please
specify that you are on the darwin platform,
on the arm64 architecture.
node:internal/fs/utils:323
    throw err;
    ^

Error: ENOENT: no such file or directory, copyfile 'exe/bs-emotion-ppx-darwin-arm64.exe'-> 'ppx'
    at Object.copyFileSync (node:fs:2068:3)
    at copyFileSync (/Users/patrick/code/draftbit/draftbit/builder/node_modules/@ahrefs/bs-emotion-ppx/copyPlatformBinaryInPlace.js:52:8)
    at copyBinary (/Users/patrick/code/draftbit/draftbit/builder/node_modules/@ahrefs/bs-emotion-ppx/copyPlatformBinaryInPlace.js:39:5)
    at Object.<anonymous> (/Users/patrick/code/draftbit/draftbit/builder/node_modules/@ahrefs/bs-emotion-ppx/copyPlatformBinaryInPlace.js:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',

```

**Comment by dhruska** [comment]
Seconded, it would be awesome to support Apple Silicon!
